### ISSUE TITLE
Cannot call the functions

### ISSUE THREAD

**Issue by ZeeD** [icarus-sullivan/serverless-plugin-utils#1]
Hi.
I'm trying to use this plugin to make some evaluations in the serverless.yml itself.

What I have are some custom variables. One is the application version, as present in the package.json.
In this moment I just have set up the version  '0.0.1'.

I would like to use the same variable in some places in application.yml - specifically I want to set the stage field, but I need to replace the dot ('.') with an underscore ('_').

I tried various ways, and I found this plugin. My goal is to have a variable with value "0_0_1".

the following is my try

```yaml
plugins:
  - serverless-offline
  - serverless-plugin-utils

...

custom:
  package_json_version: '${file(./package.json):version}'
  version:
    fn::join:
      delimiter: '_'
      values:
        fn::split:
          delimiter: '.'
          value: '${self:custom.package_json_version}'
  version_with_underscores: ${self:custom.version}
```

but when I run serverless print I have this output

```yaml
custom:
  package_json_version: 0.0.1
  version:
    'fn::join':
      delimiter: _
      values:
        'fn::split':
          delimiter: .
          value: 0.0.1
  version_with_underscores:
    $ref: '$["custom"]["version"]'
```

how can I use the functions to actually have the value?
