### ISSUE TITLE
Provider switch not supported

### ISSUE THREAD

**Issue by jeremy-brooks** [icarus-sullivan/serverless-plugin-utils#15]
Usage:
```
custom:
  stages:
    prd: prd
    dev: dev
    '*': dev

  config:
    environment: ${switch(${opt:stage}, ${self:custom.stages})}
```

Message aftre running `sls print --stage=dev`
```
Error: Provider switch is not supported
```

Servereless version: `4.4.7`
Plugin version: `0.2.0`
